### ISSUE TITLE
使用 Misc/Reader/Java 读取日志报错

### ISSUE THREAD

**Issue by zhangls2014** [HuolalaTech/hll-wp-glog#3]
java.net.ProtocolException: Unexpected end group
	at com.squareup.wire.ProtoReader.nextTag(ProtoReader.kt:152)
	at glog.android.sample.Log$ProtoAdapter_Log.decode(Log.java:335)
	at glog.android.sample.Log$ProtoAdapter_Log.decode(Log.java:286)
	at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:321)
	at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:319)
	at glog.reader.java.Main.readLogs(Main.java:38)
	at glog.reader.java.Main.main(Main.java:13)

**Comment by mricefox** [comment]
是否修改了 .proto 文件内容？读写时使用的的 .proto  文件需要保持一致
